### ISSUE TITLE
Wazuh Release 3.13.0_7.7.1

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#101]
Wazuh version: 3.13.0
Elastic version: 7.7.1

### Tasks

- [x] Adapt to new versions (3.13.0 - 7.7.1)

- [x] Update changelog

- [x] Check templates and update them if needed

- [x] Tests

- [ ] Tag: v3.13.0_7.7.1

- [x] Update documentation references

- [ ] Draft release
