### ISSUE TITLE
Wazuh Chef Release 3.13.1_7.8.0

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-chef#103]
Wazuh version: 3.13.1
Elastic version: 7.8.0

### Tasks

- [ ] Adapt to new versions (3.13.1 - 7.8.0)

- [ ] Update changelog

- [ ] Check templates and update them if needed

- [ ] Tests

- [ ] Tag: v3.13.1_7.8.0

- [ ] Update documentation references

- [ ] Draft release
