### ISSUE TITLE
Adapt cookbooks installation to Wazuh v4.1.0 new features

### ISSUE THREAD

**Issue by sergiogp98** [wazuh/wazuh-chef#128]
**Descrption**
This issue add new features added in Wazuh new version 4.1.0 ([CHANGELOG](https://github.com/wazuh/wazuh-documentation/blob/4.1/source/release-notes/release_4_1_0.rst)). Also add certificates to Elastic basic license installation cookbooks.
 
**TAG**
v4.1.0

**COOKBOOKS**
List of updated cookbooks:

- opendistro
- filebeat-oss
- elastic-stack
- filebeat
- wazuh-manager
- wazuh-agent

**TODO**

- [x] Bump to Wazuh v4.1.0 all cookbooks
- [x] Add xpack certificates (elastic-stack, filebeat)
- [x] Add all-in-one installation method
- [x] Test distributed installation method
- [x] Upgrade Inspec tests
- [x] Fix elasticsearch customize password via HTTP PUT request
- [x] Add network.rb file to opendistro installation
- [x] Update README documentation

Regards,
SG

**Comment by sergiogp98** [comment]
**Elastic basic license**

![image](https://user-images.githubusercontent.com/26262712/108552810-18e14280-72f2-11eb-99ae-49166d7c452f.png)

**Opendistro**

![image](https://user-images.githubusercontent.com/26262712/108552566-c869e500-72f1-11eb-936d-f0cb82e44a8e.png)

**Comment by sergiogp98** [comment]
**Update - 22/02**

- Add Elasticsearch customize password

```
# Generate credentials for all the Elastic Stack pre-built roles and users

execute 'Create random Elastic passwords' do 
  command "#{node['elastic']['package_path']}/bin/elasticsearch-setup-passwords auto -b > #{node['log']['passwd']}"
  not_if{
    File.exist?("#{node['log']['passwd']}")
  }
end

bash 'Set up Elastic password' do
  code <<-EOH
  ELASTIC_PASSWORD=`grep -E \"elastic = [a-zA-Z0-9]*\" #{node['log']['passwd']} | awk -F[' '] '{print $4}'`
  curl -XPOST https://elk-single-node:9200/_security/user/elastic/_password \
  -k -u elastic:$ELASTIC_PASSWORD -H \"Content-Type: application/json\" \
  -d '{\"password\" : \"#{node['network']['elasticsearch']['password']}\"}'
  EOH
  
end
```

- Adapt Inspec tests to new features

```
describe http("https://#{input('node_ip')}:#{input('elastic_port')}/_cluster/health?wait_for_status=green",
              auth: {user: "#{input('elastic_user')}", pass: "#{input('elastic_password')}"},
              ssl_verify: false,
              method: 'GET') do
  its('status') { should cmp 200 }
end 
```

- Add _network.rb_ to opendistro cookbook
