### ISSUE TITLE
Repository Refactor.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#17]
## Whole repository will be refactored in order to follow standard chef-repo structure. 

The wazuh cookbooks (Agent, Manager, API) will be split into wazuh_agent (Agent) and wazuh_manager (Manager, API) in order to differentiate roles, attributes, tests, templates and other files.

### Tasks:

- [x] Create new folders and restructure.
- [x] Divide Agent and Manager cookbooks.
    - [x] Attributes
    - [x] Recipes
    - [x] Templates
    - [x] Berksfile
    - [x] Metadata
- [x] Adapt default attributes to add v.3.9.0 features
- [x] Adapt Filebeat to v.3.9.0
- [x] Adapt ElasticStack to v.3.9.0

- [x] Rewrite README.md
    - [x]  Rewrite Agent README.md
    - [x]  Rewrite Manager README.md
    - [x]  Rewrite General README.md
    - [x] Rewrite Filebeat README.md
    - [x] Rewrite ElasticStack README.md

**Comment by manuasir** [comment]
Done here #22
