### ISSUE TITLE
Divide Agent, Manager and API cookbooks.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#18]
As stated in #17, the wazuh cookbook will be split into specific cookbooks for the agent and manager. This issue details the steps needed aswell as the process status in order to give advanced detail about this part of refactoring.

## Tasks

- [x] Split agent-specific and manager-specific attributes.
- [x] Divide specific recipes and fix names.
- [x] Fix dependencies
- [x] Separate spec recipes.
- [x] Test Agent and Manager deploy after splitting into two cookbooks.

**Comment by manuasir** [comment]
Done here #22
