### ISSUE TITLE
Adapt default attributes to add v.3.9.0 features

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#19]
Hi team!

As defined in #17 , current default attributes don't implement the new features added in 3.9.0.
The implementation of new default attributes is required in order to generate an updated ossec.conf file to give support to the new functionalities.

### Tasks

- [x] Evaluate and list all differences between old ossec.conf (generated with gyoku) and the ossec.conf file of v.3.9

- [x] Implement new fields as default attributes.

- [x] Test the new features added.

Regards!

Jose

**Comment by manuasir** [comment]
Done here #22
