### ISSUE TITLE
Nginx SSL proxy is not included in the installation process.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#21]
Hi team!

According to https://documentation.wazuh.com/3.x/installation-guide/optional-configurations/kibana_ssl.html Nginx can be configured to secure the communications with Kibana.

The current installation process does not support it. An approach could be to include a template and declare attributes to customize the Nginx configuration.

**Tasks to Do**

- [x] Add the corresponding Recipe.
- [x] Add the required dependencies.
- [x] Parameter[ize] the recipe the most possible.
- [x] Test the changes on different OS/platforms
- - [x]  Debian based distributions.
- - [x] RPM-based distributions.

Best regards!

Jose

**Comment by rshad** [comment]
Hi all!

We now have NGINX SSL Authentication implemented in wazuh-chef in order to encrypt the connections to Kibana APP.

To do so, we added the corresponding recipe and all the required dependencies, templates, etc ..

We created a new recipe in the cookbook wazuh-elastic, called `nginx.rb` .

**Recipe Tasks**

**1. Installing NGINX**

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/recipes/nginx.rb#L1-L11

**2. Create the directory `/etc/ssl/certs` and  `/etc/ssl/private`** 

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/recipes/nginx.rb#L14-L18

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/recipes/nginx.rb#L20-L24

**3. Generate a self-signed certificate and a key.**

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/recipes/nginx.rb#L26-L30

**4. Add the corresponding template for `/etc/nginx/sites-available/default`:** 

[`wazuh-chef/cookbooks/wazuh_elastic/templates/default/nginx.erb`](https://github.com/wazuh/wazuh-chef/blob/feature-21-add-nginx-authentication/cookbooks/wazuh_elastic/templates/default/nginx.erb)

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/templates/default/nginx.erb#L1-L20

To override the one already comes with Nginx installation, we added the task:

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/recipes/nginx.rb#L32-L37

**5. Install `apache2-utils` in case it does not exist.**

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/recipes/nginx.rb#L39-L49

**6. Generate a `user:password` file for Kibana authentication, using `htpasswd` resource.**

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/recipes/nginx.rb#L54-L57

We got an issue when running this task, getting the error message:
```
ERROR: cannot load such file -- htauth
```

After some investigation we think that's related some incompatibility between Chef and Htpasswd versions and however we tried with different versions of Htpasswd but none of them worked.

To solve this issue, we had to override the default installation method, and so we chose ruby to install it explicitly and not chef, using the following configuration in the recipe `nginx.rb`:

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/recipes/nginx.rb#L51-L52

**7. Finally, restart Nginx service.**

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/recipes/nginx.rb#L59-L62


----------------------------

**Do not forget about the Dependencies**

For the configurations described above, we used a new function `htpasswd` which comes from the Gem `Htpasswd` and it was not already included in the cookbook,. To do so, we had to:

1. Edit `wazuh-chef/cookbooks/wazuh_elastic/Berksfile /`

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/Berksfile#L7

2. Edit `wazuh-chef/cookbooks/wazuh_elastic/metadata.rb /`

https://github.com/wazuh/wazuh-chef/blob/abc2ce576fba11e8ccc3b3021215536d4cd36255/cookbooks/wazuh_elastic/metadata.rb#L23

-----------------

**Testing**

We tested this configuration on Debian/Ubuntu environment, but still pending to test it on Centos.

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

Just in case you want to take a look over a successful cookbook installation's log, here you have it.

**Successful Attempt Log**

```ruby
root@node-manager-1:/var/log/nginx# chef-client                                                                                                                                        root@node-manager-1:/var/log/nginx# vim /etc/kibaStarting Chef Client, version 14.14.29                                                                                                     rse-i-search)`q':     return 301 https://$host$request_uri;
resolving cookbooks for run list: ["wazuh_elastic::default"]Synchronizing Cookbooks:                                                                                                                                                                                                   root@node-man  - wazuh_elastic (0.0.2)                                                                                                                                                 root@node-manager-1:/var/log/nginx# vim /etc/kibana/kibana.yml  - apt (7.2.0)                                                                                                                            1:/var/log/nginx# systemctl restart kibana
  - chef-sugar (5.0.4)                                                                                                                     default  - poise-python (1.7.0)                                                                                                                                                                                      root@node-manager-1:/var/l  - poise-languages (2.1.2)                                                                                                                                  root@node-manager-1:/var/log/nginx#
  - poise (2.8.2)                                                                                                                          inx# systemctl restart nginx
  - poise-archive (1.5.0)  - hostsfile (3.0.1)      - yum (5.1.0)
  - htpasswd (0.3.0)     
Installing Cookbook Gems:
Compiling Cookbooks...[2019-11-08T17:18:53+00:00] WARN: chef-sugar::default no longer needs to be included in your runlist. Instead simply depend on the chef-sugar cookbook and the gem will be installed and loaded automatically.
Converging 26 resources
Recipe: wazuh_elastic::repository
  * apt_package[lsb-release] action install (up to date)  * ohai[reload lsb] action reload
    - re-run ohai and merge results into node attributes
  * apt_repository[elastic-7.x] action add (skipped due to not_if)
Recipe: wazuh_elastic::nginx
  * apt_package[nginx] action install (up to date)
  * directory[/etc/ssl/certs] action create (up to date)
  * directory[/etc/ssl/private] action create (up to date)        
  * bash[Generate a self-signed ceritificate and a key] action run
    - execute "bash"  "/tmp/chef-script20191108-24756-hagi4k" 
  * template[/etc/nginx/sites-available/default] action create (up to date)
  * apt_package[apache2-utils] action install (up to date)
Recipe: htpasswd::ruby
  * gem_package[htauth] action install (up to date)
Recipe: wazuh_elastic::nginx
  * htpasswd[/etc/nginx/conf.d/kibana.htpasswd] action add (up to date)
  * service[nginx] action restart
    - restart service service[nginx]
Recipe: wazuh_elastic::elasticsearch
  * apt_package[elasticsearch] action install (up to date)
  * template[/etc/elasticsearch/elasticsearch.yml] action create
    - change owner from 'elasticsearch' to 'root'
  * template[/etc/elasticsearch/jvm.options] action create
    - change owner from 'elasticsearch' to 'root'
  * bash[insert_line_limits.conf] action run (skipped due to not_if)
  * service[elasticsearch] action enable (up to date)
  * service[elasticsearch] action start (up to date)
  * ruby_block[wait for elasticsearch] action run
    - execute the ruby block wait for elasticsearch
  * bash[Verify Elasticsearch folders owner] action run
    - execute "bash"  "/tmp/chef-script20191108-24756-1h92a56"
Recipe: wazuh_elastic::kibana
  * apt_package[kibana] action install (up to date)
  * template[kibana.yml] action create
    - update content in file /etc/kibana/kibana.yml from 17ee81 to f418fe
    --- /etc/kibana/kibana.yml  2019-11-08 16:55:05.771728788 +0000
    +++ /etc/kibana/.chef-kibana20191108-24756-1s1slho.yml      2019-11-08 17:18:56.130164703 +0000
    @@ -7,7 +7,7 @@
     # Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
     # The default is 'localhost', which usually means remote machines will not be able to connect.
     # To allow connections from remote users, set this parameter to a non-loopback address.
    -server.host: 0.0.0.0 
    +server.host: 0.0.0.0
     
     # Enables you to specify a path to mount Kibana at if you are running behind a proxy.
     # Use the `server.rewriteBasePath` setting to tell Kibana if it should remove the basePath
  * service[kibana] action restart
    - restart service service[kibana]
  * ruby_block[wait for elasticsearch] action run
    - execute the ruby block wait for elasticsearch
  * bash[Waiting for elasticsearch curl response...] action run
    - execute "bash"  "/tmp/chef-script20191108-24756-1hs6msf"
  * bash[Install Wazuh-APP (can take a while)] action run (up to date)
  * bash[Verify Kibana folders owner] action run
    - execute "bash"  "/tmp/chef-script20191108-24756-1v8ho7r"
Recipe: wazuh_elastic::elasticsearch
  * service[elasticsearch] action restart
    - restart service service[elasticsearch]

Running handlers:
Running handlers complete
Chef Client finished, 13/28 resources updated in 17 seconds
root@node-manager-1:/var/log/nginx#
```

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

Here you have a sample output of a successful attempt for `wazuh-elastic` cookbook deployment on **Centos**.

```ruby
root@9ae84d1cdb48:~/wazuh-chef/cookbooks/wazuh_manager# kitchen converge .*elastic.*centos.*
-----> Starting Test Kitchen (v2.3.4)
-----> Converging <elastic-centos-kitchen-chef>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.8...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing environments  
       Preparing secret        
       Preparing validation.pem
       Preparing client.rb     
-----> Chef installation detected (install only if missing)
       Transferring files to <elastic-centos-kitchen-chef>
       Starting Chef Infra Client, version 15.4.45
       [2019-11-12T11:17:17+00:00] WARN: Plugin Network: unable to detect ipaddress
       resolving cookbooks for run list: ["wazuh_elastic::repository", "wazuh_elastic::elasticsearch", "wazuh_elastic::nginx", "wazuh_elastic::kibana"]
       Synchronizing Cookbooks:
         - apt (7.2.0)
         - yum (5.1.0)
         - htpasswd (0.3.0)    
         - poise-python (1.7.0)
         - chef-sugar (5.0.4)   
         - hostsfile (3.0.1)    
         - wazuh_elastic (0.0.2)
         - poise (2.8.2)
         - poise-languages (2.1.2)
         - poise-archive (1.5.0)  
       Installing Cookbook Gems:  
       Compiling Cookbooks...
       Converging 27 resources
       Recipe: wazuh_elastic::repository
         * yum_repository[elastic-7.x] action create (skipped due to not_if)
       Recipe: wazuh_elastic::elasticsearch
         * yum_package[elasticsearch] action install (up to date)
         * template[/etc/elasticsearch/elasticsearch.yml] action create
           - change owner from 'elasticsearch' to 'root'
         * template[/etc/elasticsearch/jvm.options] action create
           - change owner from 'elasticsearch' to 'root'
         * bash[insert_line_limits.conf] action run (skipped due to not_if)
         * service[elasticsearch] action enable (up to date)
         * service[elasticsearch] action start (up to date)
         * ruby_block[wait for elasticsearch] action run
           - execute the ruby block wait for elasticsearch
         * bash[Verify Elasticsearch folders owner] action run
           - execute "bash"  "/tmp/chef-script20191112-1641-1y7fzvp"
       Recipe: wazuh_elastic::nginx
         * yum_package[epel-release] action install
           - install version 0:7-11.noarch of package epel-release
         * yum_package[nginx] action install
           - install version 1:1.16.1-1.el7.x86_64 of package nginx
         * directory[/etc/nginx/sites-available] action create
           - create new directory /etc/nginx/sites-available
           - change mode from '' to '0755'
         * directory[/etc/nginx/sites-enabled] action create
           - create new directory /etc/nginx/sites-enabled
           - change mode from '' to '0755'
         * directory[/etc/ssl/certs] action create (up to date)
         * directory[/etc/ssl/private] action create
           - create new directory /etc/ssl/private
           - change mode from '' to '0755'
         * bash[Generate a self-signed ceritificate and a key] action run
           - execute "bash"  "/tmp/chef-script20191112-1641-1decwaw"
         * template[/etc/nginx/sites-available/default] action create
           - create new file /etc/nginx/sites-available/default
           - update content in file /etc/nginx/sites-available/default from none to ed882b
           --- /etc/nginx/sites-available/default       2019-11-12 11:18:22.072642529 +0000
           +++ /etc/nginx/sites-available/.chef-default20191112-1641-dgjdet     2019-11-12 11:18:22.072642529 +0000
           @@ -1 +1,21 @@
           +server {
           +    listen 80;
           +    listen [::]:80;
           +    return 301 https://$host$request_uri;
           +}
           +
           +server {
           +    listen 443 default_server;
           +    listen            [::]:443;
           +    ssl on;
           +    ssl_certificate /etc/ssl/certs/kibana-access.pem;
           +    ssl_certificate_key /etc/ssl/private/kibana-access.key;
           +    access_log            /var/log/nginx/nginx.access.log;
           +    error_log            /var/log/nginx/nginx.error.log;
           +    location / {
           +        auth_basic "Restricted";
           +        auth_basic_user_file /etc/nginx/conf.d/kibana.htpasswd;
           +        proxy_pass http://localhost:5601/;
           +    }
           +}
           - change mode from '' to '0644'
           - change owner from '' to 'root'
           - change group from '' to 'root'
       Recipe: htpasswd::ruby
         * gem_package[htauth] action install
           - install version 2.0.0 of package htauth
       Recipe: wazuh_elastic::nginx
         * htpasswd[/etc/nginx/conf.d/kibana.htpasswd] action add
           - Create htpasswd[/etc/nginx/conf.d/kibana.htpasswd]
           * ruby_block[Creating htpasswd file /etc/nginx/conf.d/kibana.htpasswd] action run
             - execute the ruby block Creating htpasswd file /etc/nginx/conf.d/kibana.htpasswd

         * service[nginx] action restart
           - restart service service[nginx]
       Recipe: wazuh_elastic::kibana
         * yum_package[kibana] action install
           - install version 7.3.2-1 of package kibana
         * template[kibana.yml] action create
           - update content in file /etc/kibana/kibana.yml from 46d200 to f74f99
           --- /etc/kibana/kibana.yml   2019-09-06 15:37:45.000000000 +0000
           +++ /etc/kibana/.chef-kibana20191112-1641-pqw8vr.yml 2019-11-12 11:19:49.992580529 +0000
           @@ -1,10 +1,13 @@
           +# The default roles file is empty as the preferred method of defining roles is
           +# through the API/UI. File based roles are useful in error scenarios when the
           +# API based roles may not be available.
            # Kibana is served by a back end server. This setting specifies the port to use.
           -#server.port: 5601
           +server.port: 5601

            # Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
            # The default is 'localhost', which usually means remote machines will not be able to connect.
            # To allow connections from remote users, set this parameter to a non-loopback address.
           -#server.host: "localhost"
           +server.host: 0.0.0.0

            # Enables you to specify a path to mount Kibana at if you are running behind a proxy.
            # Use the `server.rewriteBasePath` setting to tell Kibana if it should remove the basePath
           @@ -25,7 +28,7 @@
            #server.name: "your-hostname"

            # The URLs of the Elasticsearch instances to use for all your queries.
           -#elasticsearch.hosts: ["http://localhost:9200"]
           +elasticsearch.hosts: ['http://127.0.0.1:9200']

            # When this setting's value is true Kibana uses the hostname specified in the server.host
            # setting. When the value of this setting is false, Kibana uses the hostname of the host
           @@ -43,7 +46,7 @@
            # the username and password that the Kibana server uses to perform maintenance on the Kibana
            # index at startup. Your Kibana users still need to authenticate with Elasticsearch, which
            # is proxied through the Kibana server.
           -#elasticsearch.username: "kibana"
           +#elasticsearch.username: "user"
            #elasticsearch.password: "pass"

            # Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
           @@ -110,6 +113,5 @@
            #ops.interval: 5000

            # Specifies locale to be used for all localizable strings, dates and number formats.
           -# Supported languages are the following: English - en , by default , Chinese - zh-CN .
            #i18n.locale: "en"
           - change mode from '0644' to '0755'
         * service[kibana] action restart
           - restart service service[kibana]
         * service[kibana] action restart
           - restart service service[kibana]
         * ruby_block[wait for elasticsearch] action run
           - execute the ruby block wait for elasticsearch
         * bash[Waiting for elasticsearch curl response...] action run
           - execute "bash"  "/tmp/chef-script20191112-1641-w2tbu7"
         * bash[Install Wazuh-APP (can take a while)] action run
           - execute "bash"  "/tmp/chef-script20191112-1641-7w36il"
         * bash[Verify Kibana folders owner] action run
           - execute "bash"  "/tmp/chef-script20191112-1641-1gej3wf"
       Recipe: wazuh_elastic::elasticsearch
         * service[elasticsearch] action restart
           - restart service service[elasticsearch]
       Recipe: wazuh_elastic::kibana
         * service[kibana] action restart
           - restart service service[kibana]

       Running handlers:
       Running handlers complete
       Chef Infra Client finished, 25/31 resources updated in 03 minutes 03 seconds
       Downloading files from <elastic-centos-kitchen-chef>
       Finished converging <elastic-centos-kitchen-chef> (3m20.11s).
```

**Comment by rshad** [comment]
Hi all!

We recently worked on testing the changes on Centos, and we came through some new changes to get the complete correct functionality.

- Added Nginx recipe to default.rb. This way we can control which recipes have to be deployed and in which order.

https://github.com/wazuh/wazuh-chef/blob/a0c1b4a3ad3a1b79a8d638c6d22717ab938399f0/cookbooks/wazuh_elastic/recipes/default.rb#L11


- Added Centos' missing packages installation

https://github.com/wazuh/wazuh-chef/blob/a0c1b4a3ad3a1b79a8d638c6d22717ab938399f0/cookbooks/wazuh_elastic/recipes/nginx.rb#L1-L5

- Added ipv6only for Nginx template to avoid a possible conflict on port 80

https://github.com/wazuh/wazuh-chef/blob/a0c1b4a3ad3a1b79a8d638c6d22717ab938399f0/cookbooks/wazuh_elastic/templates/default/nginx.erb#L3

- Added Nginx attributes user: password

https://github.com/wazuh/wazuh-chef/blob/a0c1b4a3ad3a1b79a8d638c6d22717ab938399f0/cookbooks/wazuh_elastic/attributes/nginx.rb#L1-L2

- Removed unnecessary tasks and added new ones for Nginx folders creation.

https://github.com/wazuh/wazuh-chef/commit/a0c1b4a3ad3a1b79a8d638c6d22717ab938399f0

Kr,

Rshad

**Comment by rshad** [comment]
Hi all!

Here you have a sample output of a successful attempt for `wazuh-elastic` cookbook deployment on **Centos**.

```ruby
root@9ae84d1cdb48:~/wazuh-chef/cookbooks/wazuh_manager# kitchen converge .*elastic.*centos.*
-----> Starting Test Kitchen (v2.3.4)
-----> Converging <elastic-centos-kitchen-chef>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.0.8...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing environments  
       Preparing secret        
       Preparing validation.pem
       Preparing client.rb     
-----> Chef installation detected (install only if missing)
       Transferring files to <elastic-centos-kitchen-chef>
       Starting Chef Infra Client, version 15.4.45
       [2019-11-12T11:17:17+00:00] WARN: Plugin Network: unable to detect ipaddress
       resolving cookbooks for run list: ["wazuh_elastic::repository", "wazuh_elastic::elasticsearch", "wazuh_elastic::nginx", "wazuh_elastic::kibana"]
       Synchronizing Cookbooks:
         - apt (7.2.0)
         - yum (5.1.0)
         - htpasswd (0.3.0)    
         - poise-python (1.7.0)
         - chef-sugar (5.0.4)   
         - hostsfile (3.0.1)    
         - wazuh_elastic (0.0.2)
         - poise (2.8.2)
         - poise-languages (2.1.2)
         - poise-archive (1.5.0)  
       Installing Cookbook Gems:  
       Compiling Cookbooks...
       Converging 27 resources
       Recipe: wazuh_elastic::repository
         * yum_repository[elastic-7.x] action create (skipped due to not_if)
       Recipe: wazuh_elastic::elasticsearch
         * yum_package[elasticsearch] action install (up to date)
         * template[/etc/elasticsearch/elasticsearch.yml] action create
           - change owner from 'elasticsearch' to 'root'
         * template[/etc/elasticsearch/jvm.options] action create
           - change owner from 'elasticsearch' to 'root'
         * bash[insert_line_limits.conf] action run (skipped due to not_if)
         * service[elasticsearch] action enable (up to date)
         * service[elasticsearch] action start (up to date)
         * ruby_block[wait for elasticsearch] action run
           - execute the ruby block wait for elasticsearch
         * bash[Verify Elasticsearch folders owner] action run
           - execute "bash"  "/tmp/chef-script20191112-1641-1y7fzvp"
       Recipe: wazuh_elastic::nginx
         * yum_package[epel-release] action install
           - install version 0:7-11.noarch of package epel-release
         * yum_package[nginx] action install
           - install version 1:1.16.1-1.el7.x86_64 of package nginx
         * directory[/etc/nginx/sites-available] action create
           - create new directory /etc/nginx/sites-available
           - change mode from '' to '0755'
         * directory[/etc/nginx/sites-enabled] action create
           - create new directory /etc/nginx/sites-enabled
           - change mode from '' to '0755'
         * directory[/etc/ssl/certs] action create (up to date)
         * directory[/etc/ssl/private] action create
           - create new directory /etc/ssl/private
           - change mode from '' to '0755'
         * bash[Generate a self-signed ceritificate and a key] action run
           - execute "bash"  "/tmp/chef-script20191112-1641-1decwaw"
         * template[/etc/nginx/sites-available/default] action create
           - create new file /etc/nginx/sites-available/default
           - update content in file /etc/nginx/sites-available/default from none to ed882b
           --- /etc/nginx/sites-available/default       2019-11-12 11:18:22.072642529 +0000
           +++ /etc/nginx/sites-available/.chef-default20191112-1641-dgjdet     2019-11-12 11:18:22.072642529 +0000
           @@ -1 +1,21 @@
           +server {
           +    listen 80;
           +    listen [::]:80;
           +    return 301 https://$host$request_uri;
           +}
           +
           +server {
           +    listen 443 default_server;
           +    listen            [::]:443;
           +    ssl on;
           +    ssl_certificate /etc/ssl/certs/kibana-access.pem;
           +    ssl_certificate_key /etc/ssl/private/kibana-access.key;
           +    access_log            /var/log/nginx/nginx.access.log;
           +    error_log            /var/log/nginx/nginx.error.log;
           +    location / {
           +        auth_basic "Restricted";
           +        auth_basic_user_file /etc/nginx/conf.d/kibana.htpasswd;
           +        proxy_pass http://localhost:5601/;
           +    }
           +}
           - change mode from '' to '0644'
           - change owner from '' to 'root'
           - change group from '' to 'root'
       Recipe: htpasswd::ruby
         * gem_package[htauth] action install
           - install version 2.0.0 of package htauth
       Recipe: wazuh_elastic::nginx
         * htpasswd[/etc/nginx/conf.d/kibana.htpasswd] action add
           - Create htpasswd[/etc/nginx/conf.d/kibana.htpasswd]
           * ruby_block[Creating htpasswd file /etc/nginx/conf.d/kibana.htpasswd] action run
             - execute the ruby block Creating htpasswd file /etc/nginx/conf.d/kibana.htpasswd

         * service[nginx] action restart
           - restart service service[nginx]
       Recipe: wazuh_elastic::kibana
         * yum_package[kibana] action install
           - install version 7.3.2-1 of package kibana
         * template[kibana.yml] action create
           - update content in file /etc/kibana/kibana.yml from 46d200 to f74f99
           --- /etc/kibana/kibana.yml   2019-09-06 15:37:45.000000000 +0000
           +++ /etc/kibana/.chef-kibana20191112-1641-pqw8vr.yml 2019-11-12 11:19:49.992580529 +0000
           @@ -1,10 +1,13 @@
           +# The default roles file is empty as the preferred method of defining roles is
           +# through the API/UI. File based roles are useful in error scenarios when the
           +# API based roles may not be available.
            # Kibana is served by a back end server. This setting specifies the port to use.
           -#server.port: 5601
           +server.port: 5601

            # Specifies the address to which the Kibana server will bind. IP addresses and host names are both valid values.
            # The default is 'localhost', which usually means remote machines will not be able to connect.
            # To allow connections from remote users, set this parameter to a non-loopback address.
           -#server.host: "localhost"
           +server.host: 0.0.0.0

            # Enables you to specify a path to mount Kibana at if you are running behind a proxy.
            # Use the `server.rewriteBasePath` setting to tell Kibana if it should remove the basePath
           @@ -25,7 +28,7 @@
            #server.name: "your-hostname"

            # The URLs of the Elasticsearch instances to use for all your queries.
           -#elasticsearch.hosts: ["http://localhost:9200"]
           +elasticsearch.hosts: ['http://127.0.0.1:9200']

            # When this setting's value is true Kibana uses the hostname specified in the server.host
            # setting. When the value of this setting is false, Kibana uses the hostname of the host
           @@ -43,7 +46,7 @@
            # the username and password that the Kibana server uses to perform maintenance on the Kibana
            # index at startup. Your Kibana users still need to authenticate with Elasticsearch, which
            # is proxied through the Kibana server.
           -#elasticsearch.username: "kibana"
           +#elasticsearch.username: "user"
            #elasticsearch.password: "pass"

            # Enables SSL and paths to the PEM-format SSL certificate and SSL key files, respectively.
           @@ -110,6 +113,5 @@
            #ops.interval: 5000

            # Specifies locale to be used for all localizable strings, dates and number formats.
           -# Supported languages are the following: English - en , by default , Chinese - zh-CN .
            #i18n.locale: "en"
           - change mode from '0644' to '0755'
         * service[kibana] action restart
           - restart service service[kibana]
         * service[kibana] action restart
           - restart service service[kibana]
         * ruby_block[wait for elasticsearch] action run
           - execute the ruby block wait for elasticsearch
         * bash[Waiting for elasticsearch curl response...] action run
           - execute "bash"  "/tmp/chef-script20191112-1641-w2tbu7"
         * bash[Install Wazuh-APP (can take a while)] action run
           - execute "bash"  "/tmp/chef-script20191112-1641-7w36il"
         * bash[Verify Kibana folders owner] action run
           - execute "bash"  "/tmp/chef-script20191112-1641-1gej3wf"
       Recipe: wazuh_elastic::elasticsearch
         * service[elasticsearch] action restart
           - restart service service[elasticsearch]
       Recipe: wazuh_elastic::kibana
         * service[kibana] action restart
           - restart service service[kibana]

       Running handlers:
       Running handlers complete
       Chef Infra Client finished, 25/31 resources updated in 03 minutes 03 seconds
       Downloading files from <elastic-centos-kitchen-chef>
       Finished converging <elastic-centos-kitchen-chef> (3m20.11s).
``` 

Kr,

Rshad
