### ISSUE TITLE
Chef  doesn't generate Agent.conf files

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#31]
Hi team,

The current code doesn't allow the user to generate the *Agent.conf* that is required in a [centralized configuration](https://documentation.wazuh.com/3.x/user-manual/reference/centralized-configuration.html).

### Tasks:

- [x] Implement the generation of *Agent.conf* with Gyoku

- [x] Add configuration of `wazuh_command.remote_commands=1` for Wazuh Agent.

- [x] Implement some form of verification of *Agent.conf* file

- [x] Test changes

- [x] Update README.md

**Comment by manuasir** [comment]
Done here #46
