### ISSUE TITLE
Implement Kitchen tests for installation verification.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#34]
Hi team,

It's possible to test the integration and configuration of Wazuh Installation by using [Kitchen](https://kitchen.ci/docs/) for Chef. Kitchen provides a driver-plugin architecture to run cookbooks against different platforms.

This implementation would provide a much easier way to test future changes and updates.

### Tasks:

- [x] Design and create tests.
- [x] Run tests against different platforms and verify results.
- [x] Update Readme.md

Best Regards,

Jose

**Comment by rshad** [comment]
Hi all,

Since Friday, August 2nd, till Today we completed the required changes in order to resolve this issue.

In order to do so we worked with the following tools:
* Kitchen-Chef
* Kitchen-docker

Our root folder was considered to be [`wazuh-manager`](https://github.com/wazuh/wazuh-chef/tree/3.9.4_7.2.0_kitchen/cookbooks/wazuh_manager) cookbook.

The first step to do was to define the paths for each cookbook to be used in `kitchen.yml`, and to do so we have to provide such information in the file `Berksfile`:

```
source 'https://supermarket.chef.io'

metadata

cookbook 'chef-sugar'
cookbook 'hostsfile'
cookbook 'apt'
cookbook 'yum'
cookbook 'poise-python'
cookbook 'wazuh_filebeat', path: '/home/vagrant/wazuh-chef/cookbooks/wazuh_filebeat/'
cookbook 'wazuh_agent', path: '/home/vagrant/wazuh-chef/cookbooks/wazuh_agent/'
cookbook 'wazuh_elastic', path: '/home/vagrant/wazuh-chef/cookbooks/wazuh_elastic/'
```

And to make things more dynamic, we defined an environment variable. `COOKBOOKS_HOME`
```
export COOKBOOKS_HOME=/home/vagrant/wazuh-chef/cookbooks
```

Once the dependencies described in `Berksfile` are installed "using `berks install` if they're not", then we can start configuring `kitchen.yml` file as follows:

**1. Configuration for `kitchen.yml`**

**1.1 Defining Driver, Provisioner, and Platforms**
```
---
driver:
  name: docker
  privileged: true
  use_sudo: false

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu
    driver_config:
      image: ubuntu:14.04
      platform: ubuntu

  - name: centos
    driver_config:
      image: centos:7
      platform: centos
      run_command: /usr/sbin/init
      dockerfile: test/Dockerfile
      build_options:
        rm: true
```

In this case, we use `docker` as a driver, `chef_zero` as provisioner "we can also use `chef_solo`" and (`ubuntu and centos`) as platforms.

**1.2 Defining Suites**

```
suites:
  - name: manager
    environments_path: <%= ENV['COOKBOOKS_HOME'] %>/wazuh_manager/test/environments
    data_bags_path: <%= ENV['COOKBOOKS_HOME'] %>/wazuh_manager/test/data_bags
    encrypted_data_bag_secret_key_path: <%= ENV['COOKBOOKS_HOME'] %>/wazuh_manager/test/data_bags/wazuh_secrets/test_data_bag_key
    driver:
    run_list:
      - recipe[wazuh_manager::repository]
      - recipe[wazuh_manager::manager]
      - recipe[wazuh_filebeat::default]
    attributes:
    provisioner:
      client_rb:
        environment: development-master
    verifier:
      name: shell
      command: py.test -v test/base

  - name: agent
    environments_path: <%= ENV['COOKBOOKS_HOME'] %>/wazuh_agent/test/environments
    data_bags_path: <%= ENV['COOKBOOKS_HOME'] %>/wazuh_agent/test/data_bags
    encrypted_data_bag_secret_key_path: <%= ENV['COOKBOOKS_HOME'] %>/wazuh_agent/test/data_bags/wazuh_secrets/test_data_bag_key
    driver:
    run_list:
      - recipe[wazuh_agent::repository]
      - recipe[wazuh_agent::agent]
    attributes:
         vagrant:
    provisioner:
      client_rb:
        environment: development
    verifier:
      name: shell
      command: py.test -v test/base
```

In this case, we have 2 suites, one for the Manager and another for the Agent.

**2. Designing Tests**

In this case, we use `PyTest Testinfra` package. Find the designed tests [here](https://github.com/wazuh/wazuh-chef/tree/3.9.4_7.2.0_kitchen/cookbooks/wazuh_manager/test/base)!.

**3. More Automation**

In order to avoid such manual tasks to clean instances, containers, logs and running new instances each time we want to have a new test attempt, then we designed two simple `Bash` scripts:

**3.1 `clean.sh`**

Used for cleaning all related to the previous tests.

https://github.com/wazuh/wazuh-chef/blob/486d61f5d06078cebdcab4c1ce3c58cd233c5b25/cookbooks/wazuh_manager/clean.sh#L1-L15


**3.2 `run.sh`**

Used for launching a new test.

https://github.com/wazuh/wazuh-chef/blob/486d61f5d06078cebdcab4c1ce3c58cd233c5b25/cookbooks/wazuh_manager/run.sh#L1-L38

By default, it runs the test on [`ubuntu and centos`] distribution. But if you want to choose one of them only, you only need to pass the desired distribution as an argument to the script:

```
./run.sh centos # in this example we choose centos
```

Kr,

Rshad Zhran
