### ISSUE TITLE
Add ability to install and configure Agent but don't register it.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#45]
Hi team,

The ability to install Agents but don't register it is quite useful and requested by the community (see https://github.com/wazuh/wazuh-puppet/issues/106).

Adding that feature would give flexibility to the Agent installation and would ease the installation on cloud environments for example.

##### Tasks

- [x] Modify code to allow user configure if he wants to register the agent or not

- [x] Test changes with and without the flag enabled

- [x] Update README.md

Best regards

Jose

**Comment by rshad** [comment]
Hi all,

Now we give the possibility to choose to register an agent after being configured and installed in a manager. 

As @paulcalabro proposed this change in https://github.com/wazuh/wazuh-puppet/issues/106, he justified it by the following statement:

> Sometimes it's necessary to install the Wazuh agent, but not register it with a manager. For example, when working with Amazon Machine Images (AMIs). You want to reduce the time it takes to install the agent by baking the installation into the image, however, you don't want to have a duplicate client.keys files by doing registration at the time of image creation.


In order to do so, it's only needed to assign the value `yes` to the variable ` default['ossec']['agent_auth']['register'] ` in the attributes file_ ` wazuh-chef/cookbooks/wazuh_agent/0attributes/authd.rb `:

```
default['ossec']['agent_auth']['register'] = 'yes'
```

The default value is `yes`.In another case, we just assign a different value which is not `yes`.

Kind regards,

Rshad

**Comment by jm404** [comment]
Done here #50 

Regards!
