### ISSUE TITLE
New API configuration behavior on 3.11

### ISSUE THREAD

**Issue by xr09** [wazuh/wazuh-chef#77]
### Description

Starting with `v3.11` the Wazuh plugin for  Kibana has a new behavior when upgrading. 

Documented here: https://github.com/wazuh/wazuh-kibana-app/issues/1465

The former `config.yml` got renamed to `wazuh.yml`, which brought some internal changes as well, the API settings will no longer be stored in the Elastic index named `.wazuh`, these settings got migrated to `wazuh.yml`.

The new behavior is like this:

- The first time booting `3.11` Wazuh plugin detects if there's an `.wazuh` index and moves it to `wazuh.yml`, this info gets deleted from Elastic.

- On the following restart cycles there will be no `.wazuh` index

### Proposed workflow

Following a declarative approach we propose to always delete the `.wazuh` index if exists and write API settings to `wazuh.yml`. In the case the user updated the password, then the cookbook will override it in both the API and Kibana settings.

### Tasks

- [x] Implement required changes to make Chef delete the `.wazuh` index

- [x] Add required variables to configure the API credentials in the `wazuh.yml` file

- [x] Create template to render the `wazuh.yml` file

### Tests

The following scenarios should be tested:

- [x] New deployment
- [x] Upgrading from `3.10` to `3.11` (no other changes)
- [x] Upgrading from `3.10` to `3.11` (changing API settings)

**Comment by jm404** [comment]
### Implement changes to configure Wazuh API credentials

The Chef code now checks for existent `.wazuh` index and removes it in case it exists. Also, a `template` block has been added to configure the Wazuh API credentials for Kibana:

![image](https://user-images.githubusercontent.com/46649922/71593076-d92a2b00-2b32-11ea-90e2-81e6392960f4.png)

**Commit:** https://github.com/wazuh/wazuh-chef/commit/0cdeba64bf8108e14946939205ce54637c5c8203

**Comment by jm404** [comment]
Done in #78
