### ISSUE TITLE
Old Wazuh Kibana plugin is not removed in upgrades

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-chef#79]
When deploying a newer version of Wazuh, there are no checks to verify if an older Wazuh Kibana Plugin exists, this may lead to newer Kibana versions using old plugin versions which leads to the following error:

```
Dec 31 10:52:38 node-manager-1 kibana[17154]: FATAL  TypeError: Cannot read property 'version' of undefined
```

### Tasks

- [x] Implement required changes to uninstall old Wazuh Kibana Plugin

### Tests

- [x] Test Kibana upgrade and verify the plugin is properly removed

- [x] Test Kibana clean installation

Best regards,

Jose

**Comment by jm404** [comment]
### Add bash block to remove old Wazuh Kibana plugin

The following block has been added:

![image](https://user-images.githubusercontent.com/46649922/71620184-ceba7080-2bc8-11ea-8126-d3b4ef9424c1.png)

**Commit:** https://github.com/wazuh/wazuh-chef/commit/0b3c4edddfe6969764a920bd21a9220bae432f81

**Comment by jm404** [comment]
Done in #80
