### ISSUE TITLE
Wazuh Chef release v3.12.3_7.6.2

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-chef#99]
Wazuh version: 3.12.3
Elastic version: 7.6.2

### Tasks

- [x] Adapt to new versions (3.12.3 - 7.6.2)

- [x] Update changelog

- [x] Check templates and update them if needed

- [x] Tests

- [x] Tag: v3.12.3_7.6.2

- [x] Update documentation references

- [x] Draft release
